### PR TITLE
Added file editor feature for resources and directories

### PR DESCRIPTION
**Pull request by mzereba**

### CODE REVIEW

**Comment by deiu** [comment]
Ugh....this is not the best place to send you pull request to. This repository is only used to host WARP (the app) on gh-pages. The original project's source code is at https://github.com/deiu/warp. Is there any chance you can clone that and submit a PR there? Thanks!

**Comment by mzereba** [comment]
So if I understood correctly, you want me to pull from https://github.com/deiu/warp , apply my changes and push it back up in order to do a pull request for you there?

Maged Zereba
Senior Software Engineer
Distributed Systems

Qatar Computing Research Institute
13th floor, Tornado Tower
Doha, Qatar
Tel:  +974 4454 1435tel:+974%204454%201435
Mob: +974 5598 0604tel:+974%205598%200604
www.qcri.qahttp://www.qcri.org/

On Dec 8, 2014, at 18:04, "Andrei" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ugh....this is not the best place to send you pull request to. This repository is only used to host the application on gh-pages. The original project's source code is at https://github.com/deiu/warp. Is there any chance you can clone that and submit a PR there? Thanks!

—
Reply to this email directly or view it on GitHubhttps://github.com/linkeddata/warp/pull/2#issuecomment-66127791.

CONFIDENTIALITY  NOTICE:
This email and any attachments transmitted with it are confidential and intended for the use of individual or entity to which it is addressed. If you have received this email in error, please delete it immediately and inform the sender. Unless you are the intended recipient, you may not use, disclose, copy or distribute this email or any attachments included. The contents of the emails including any attachments may be subjected to copyrights law, In such case the contents may not be copied, adapted, distributed or transmitted without the consent of the copyright owner.

**Comment by deiu** [comment]
Yes, exactly. I'm sorry, I should have mentioned that this isn't the right repository from the begining.

**Comment by mzereba** [comment]
Andrei,

I forked the project from the location you gave me, applied my changes and after committing I created a pull request for you.

Although I didn’t have chance to run it to test it, even if the changes are already tested on the other version but still. Could you please let me know how you call the app from the browser since I tried to run it like the other one but no luck.

Thanks,

[Description: Description: cid:image002.png@01CDD200.14D811B0]

Maged Zereba
Senior Software Engineer
Distributed Systems

Qatar Computing Research Institute
13th floor, Tornado Tower
Doha, Qatar
Tel:  +974 4454 1435
Mob: +974 5598 0604
www.qcri.qahttp://www.qcri.org/
[Description: Description: Facebook]https://www.facebook.com/QCRI.QA?fref=ts[Description: Description: Twitter]https://twitter.com/qatarcomputing[Description: Description: Youtube]http://www.youtube.com/user/QatarComputing

**Pull request closed without merging**
